apiVersion: batch/v1 # Jobs Default K8 API
kind: Job # This tells kubernetes what kind of class it is working with
metadata:
  name: donnie-imagenet-v2-preprocessing # Name of the Job
spec:
  parallelism: 10
  template: # Pod Templete
    spec:
      volumes:
          - name: mnt
            hostPath:
              path: /mnt
      restartPolicy: Never # Options are Always, OnFailure, and Never.
      hostNetwork: true # This option will allow the pod to use the host network for internet access
      containers:
      - name: donnie-imagenet-v2-preprocessing # Container name (Can be set to whatever)
        image: at-docker.ad.bcm.edu:5000/stimulus-pipeline:latest # Docker Image hosted on at-docker.ad.bcm.edu:5000
        resources:
              requests:
                memory: 16Gi
                # storage: 64Gi
                cpu: 12
        volumeMounts:
            - name: mnt
              mountPath: /mnt
        env:
        - name: DJ_HOST
          valueFrom:
            secretKeyRef:
              name: datajoint-credentials
              key: DJ_HOST
        - name: DJ_USER
          valueFrom:
            secretKeyRef:
              name: datajoint-credentials
              key: DJ_USER
        - name: DJ_PASS
          valueFrom:
            secretKeyRef:
              name: datajoint-credentials
              key: DJ_PASS
        - name: GITHUB_USERNAME
          valueFrom:
            secretKeyRef:
              name: github-credentials
              key: GITHUB_USERNAME
        - name: GITHUB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: github-credentials
              key: GITHUB_PASSWORD
        command: ["/bin/bash"]
        args: ["-c", "git clone https://$(GITHUB_USERNAME):$(GITHUB_PASSWORD)@github.com/donniekim411/stimuli.git && python3 -u /data/stimuli/script/populate_imagenet_v2.py"] # sh commands to clone and run python script